#!/bin/sh

version=$(git describe --abbrev=0 --tags)
name="xsv-$version-x86_64-unknown-linux-gnu"

github-release release --user jqnatividad --repo xsv --tag $version \
  --name "xsv-$version" --pre-release
