#!/bin/sh

version=$(git describe --abbrev=0 --tags)
name="qsv-$version-x86_64-unknown-linux-gnu"

github-release release --user jqnatividad --repo qsv --tag $version \
  --name "qsv-$version" --pre-release
